### ISSUE TITLE
call functions in different c# files scripts

### ISSUE THREAD

**Issue by delaurean** [keijiro/KlakUI#1]
Hi, keijiro. I´m Laureano from Argentina, trying to make my VJ set on unity.
Thanks for sharing all your projects they are really helpful.

I am trying to use KlakUi for controlling some simple functions that i have wrote.
How do I call a function on another file?  Can you gave me a tip on that.
Ore have any example where I can see how you connect them?
Thanks and congratulations on your work.

**Comment by keijiro** [comment]
Sorry for not replying. You can use an Event node to call a public function in any component.
